version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    timezone: America/New_York
  open-pull-requests-limit: 10
  reviewers:
  - namoscato
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
